### ISSUE TITLE
crates.io?

### ISSUE THREAD

**Issue by TheBotlyNoob** [AlvaroMS25/zephyrus#1]
When will you upload this crate to https://crates.io?

**Comment by AlvaroMS25** [comment]
I'm planning to upload it the next week, i'm currently trying to avoid Boxing in [parse](https://github.com/AlvaroMS25/zephyrus/blob/master/src/parse.rs#L34-L36) and i want to write some basic documentation for the parse derive macro

**Comment by AlvaroMS25** [comment]
This crate is now at crates io at https://crates.io/crates/zephyrus
