### ISSUE TITLE
HTTP interactions support

### ISSUE THREAD

**Issue by randomairborne** [AlvaroMS25/zephyrus#2]
Does this framework support interactions over HTTP?

**Comment by AlvaroMS25** [comment]
It shouldn't be a problem as long as you can get an `Interaction` object. Maybe you can get it by deserializing the request?

**Comment by randomairborne** [comment]
That should actually work just fine.

**Comment by randomairborne** [comment]
Actually, zephyrus does not seem to support responding directly to slashes. I can hardcode it to a "thinking" response, but that's kind of a shame.

**Comment by AlvaroMS25** [comment]
do you mean responding to the ping sent by discord by a post request?

**Comment by randomairborne** [comment]
No, just responding with JSON in general, rather then using a webhook response

**Comment by AlvaroMS25** [comment]
Well, the response implementation is dependent on the crate you're using, so i don't think writing a generic implementation would be possible.
