### ISSUE TITLE
Context Menu Commands

### ISSUE THREAD

**Issue by Fyko** [AlvaroMS25/zephyrus#6]
Hey there, loving the framework! The only thing currently holding me back from using it 100% is the lack of support for [user](https://discord.com/developers/docs/interactions/application-commands#user-commands) and [message](https://discord.com/developers/docs/interactions/application-commands#message-commands) context menu commands.

I'd love to try and write the implementation myself, but I'm not sure where to begin.  

The difference between slash commands and these context commands are:
- they take zero options
- their data object only has two field:
  - `name`, the name of the command, can have spaces
  - `type`, `2` for user, `3` for message

My questions are: 
- Should we use the existing `#[command]` attr and add something to it?
  - If not, do we need two new attrs, `#[user_command]`, and `#[message_command]`?
    - If so, how does that clash with [`FrameworkBuilder#command`](https://docs.rs/zephyrus/latest/zephyrus/builder/struct.FrameworkBuilder.html#method.command)

**Comment by AlvaroMS25** [comment]
Hi!
I'd love to bring all types of commands into the framework!
I'm busy with college exams and haven't had time to work more on it, but i'm planning to merge [darling](https://github.com/AlvaroMS25/zephyrus/tree/darling) branch into master today after i change a few things (in the following days if i don't have the time today)

With that, creating new macros or modifying existing ones should be way easier, so either something like 
`#[command(chat/user/message)]` or `#[{user/message}_command]` should be fairly easy to implement (along with all missing localization stuff)

**Comment by AlvaroMS25** [comment]
The problem i see here is how to create them without making a mess, maybe commands could get something like:
```rs

impl Command {
    // This should not be needed when dealing with groups, since they can only be CHAT_INPUT
    async fn create(&self, http: &InteractionClient, guild: Option<Id<GuildMarker>>) -> Result<TwilightCommand, Error>;
}
```

Or even user/message commands could get its own command map, but i think that is not necessary.

**Comment by AlvaroMS25** [comment]
Yo!
I've already started to implement user/message commands, i've finished rewriting commands & groups creation logic and now i have to start with the macros.

I've decided to make the macros look like `#[command({chat, user, message})`
If no command type is specified, it'll assume it is a chat command. I'd like to make the macro accept something like `#[command(chat, name="my_command")]` and without the `chat` specifier like `#[command(name = "my_command")]`, however i don't know if that'll be possible 🤔

**Comment by Fyko** [comment]
Good idea!

I believe you'd have to do:
`#[command("myname")]` - default to slashie
`#[command(type = message, name = "myname")]`

**Comment by AlvaroMS25** [comment]
I'll try that! I'm currently looking on how to parse the input of `#[command(whatever)]` into meta to use darling

**Comment by AlvaroMS25** [comment]
Sorry to keep you waiting!
This weekend i'll publish to crates.io the new version with the new command implementation, i only have to test it and modify docs.

The macros now accept `#[command((chat,user,message)?, (name="something")?)]`
What is surrounded by `(...)?` means it's optional, so you can either write `#[command(name="something")]`, `#[command(chat, name="something")]` or `#[command(user)]`

Right now, the macro doesn't accept something like `#[command("something")]` since i haven't found how to implement that using darling, but as the last resort i could clone the input `TokenStream` and parse it directly into a string literal like the `master` branch does.

**Comment by AlvaroMS25** [comment]
`commands` branch merged into `master` and deleted, will be publishing new crate version to crates.io in the following hours

Edit: now live at https://crates.io/crates/zephyrus
